language: node_js
branches:
  only:
    - master
node_js:
   - "8"
   - "10"
matrix:
  fast_finish: true
before_script:
  - npm i -g istanbul codeclimate-test-reporter mocha lerna
script:
  - lerna bootstrap
  - lerna run test
sudo: false
after_script:
  - istanbul cover _mocha -- --exit
  - codeclimate-test-reporter < ./coverage/lcov.info
