init:
  - git config --global core.autocrlf input

environment:
  nodejs_version: "6"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install lerna -g
  - lerna bootstrap
  - lerna run test
test_script:
  - node --version
  - npm --version
  - cmd: npm test

build: off
